name: Install dependencies
description: Install Poetry and the project's dependencies
inputs:
  atoti-plus-repository-username:
    description: The username to use to download the `atoti-plus` plugin.
    required: true
  atoti-plus-repository-password:
    description: The password to use to download the `atoti-plus` plugin.
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - uses: snok/install-poetry@v1
      with:
        version: "1.1.13"
        virtualenvs-in-project: true
    - uses: actions/cache@v2
      id: cached-poetry-venv
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-venv.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
      env:
        POETRY_HTTP_BASIC_ATOTI_PLUS_USERNAME: ${{ inputs.atoti-plus-repository-username }}
        POETRY_HTTP_BASIC_ATOTI_PLUS_PASSWORD: ${{ inputs.atoti-plus-repository-password }}
      shell: bash
    - name: Install project root
      run: poetry install --no-interaction
      shell: bash
