name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-dependencies
        with:
          atoti-plus-repository-username: ${{ secrets.ATOTI_PLUS_REPOSITORY_USERNAME }}
          atoti-plus-repository-password: ${{ secrets.ATOTI_PLUS_REPOSITORY_PASSWORD }}
      - run: poetry run app format --check
      - run: poetry run app sort-imports --check
      - run: poetry run app lint
      - run: poetry run app typecheck
      - run: poetry run app test
        env:
          ATOTI_LICENSE: ${{ secrets.ATOTI_PLUS_LICENSE }}
          ATOTI_PLUS_REPOSITORY_USERNAME: ${{ secrets.ATOTI_PLUS_REPOSITORY_USERNAME }}
          ATOTI_PLUS_REPOSITORY_PASSWORD: ${{ secrets.ATOTI_PLUS_REPOSITORY_PASSWORD }}
